import { readdir, readFile, writeFile } from "node:fs/promises";
import path from "node:path";
import matter from "gray-matter";
import { t } from "elysia";
import { check, formatErrors } from "../src/utils/validate";

const ROOT = path.resolve(process.cwd());
const SKILLS_DIR = path.join(ROOT, "skills");
const OUT = path.join(ROOT, "src", "skills.generated.ts");

const FrontmatterSchema = t.Object({
	id: t.String(),
	name: t.String(),
	description: t.String(),
	tier: t.Union([t.Literal("fast"), t.Literal("smart")]),
	mode: t.Literal("sync"),
	version: t.String(),
	cacheTtl: t.Number(),
	maxInputChars: t.Number(),
	outputMode: t.Optional(t.Union([t.Literal("object"), t.Literal("text")])),
	chunkSize: t.Optional(t.Number()),
});

const entries = await readdir(SKILLS_DIR, { withFileTypes: true });
const skillDirs = entries.filter((e) => e.isDirectory()).map((e) => e.name);

const importLines: string[] = [];
const dataLines: string[] = [];

for (let i = 0; i < skillDirs.length; i++) {
	const id = skillDirs[i];
	const skillDir = path.join(SKILLS_DIR, id);
	const raw = await readFile(path.join(skillDir, "SKILL.md"), "utf-8");
	const { data, content } = matter(raw);

	if (!check(FrontmatterSchema, data)) {
		const errs = formatErrors(FrontmatterSchema, data);
		throw new Error(`Skill "${id}" frontmatter invalid — ${errs}`);
	}

	if (data.id !== id) {
		throw new Error(`Skill "${id}": id "${data.id}" must match folder name`);
	}

	importLines.push(`import * as _m${i} from "../skills/${id}/model";`);
	importLines.push(`import * as _s${i} from "../skills/${id}/service";`);

	const fm = JSON.stringify(data, null, 2).replace(/\n/g, "\n    ");

	dataLines.push(`  {
    frontmatter: ${fm},
    systemPrompt: ${JSON.stringify(content.trim())},
    input: _m${i}.input,
    output: _m${i}.output,
    render: _s${i}.render as (input: unknown) => string,
    refine: (_s${i} as unknown as { refine?: (output: unknown, input: unknown) => unknown }).refine,
  }`);
}

const code = `// AUTO-GENERATED by scripts/gen-registry.ts — do not edit
import type { TSchema } from "elysia";
${importLines.join("\n")}

export type SkillFrontmatter = {
  id: string;
  name: string;
  description: string;
  tier: "fast" | "smart";
  mode: "sync";
  version: string;
  cacheTtl: number;
  maxInputChars: number;
  outputMode?: "object" | "text";
  chunkSize?: number;
};

export type GeneratedSkill = {
  frontmatter: SkillFrontmatter;
  systemPrompt: string;
  input: TSchema;
  output: TSchema;
  render: (input: unknown) => string;
  refine?: (output: unknown, input: unknown) => unknown;
};

export const SKILLS_DATA: GeneratedSkill[] = [
${dataLines.join(",\n")}
];
`;

await writeFile(OUT, code, "utf-8");
console.log(
	`[gen-registry] ${skillDirs.length} skills → src/skills.generated.ts`,
);
